In [90]:
import tensorflow as tf
import numpy as np
import keras


fashion_mnist = tf.keras.datasets.fashion_mnist

In [91]:
def load_fashion_mnist():
  (train_X, train_y), (test_X, test_y) = fashion_mnist.load_data()
  train_X = train_X/255.0
  test_X = test_X/255.0

  #dims 확장 ??
  train_X = np.expand_dims(train_X, axis = -1)
  test_X = np.expand_dims(test_X, axis = -1)

  train_y = tf.keras.utils.to_categorical(train_y,10)
  test_y = tf.keras.utils.to_categorical(test_y,10)

  return train_X, train_y, test_X, test_y

In [94]:
def build_cnn_model(input_shape, num_classes):
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Conv2D(filters = 16, kernel_size = (3,3),input_shape = input_shape,activation = "relu",padding = 'same'))
  model.add(tf.keras.layers.MaxPooling2D())
  #model.add(tf.keras.layers.Dropout(0.2))
  model.add(tf.keras.layers.Conv2D(filters = 32,kernel_size = (3,3), activation = "relu",padding = 'same'))
  model.add(tf.keras.layers.MaxPooling2D())
  model.add(tf.keras.layers.Conv2D(filters = 64,kernel_size = (3,3),activation = "relu",padding = 'same'))
  model.add(tf.keras.layers.MaxPooling2D())
  model.add(tf.keras.layers.Flatten())
  model.add(tf.keras.layers.Dense(128,activation = "relu"))
  model.add(tf.keras.layers.Dense(num_classes,activation = "softmax"))  


  return model


In [95]:
def main(cann_model = None, epochs = 5):
  train_X, train_y, test_X, test_y = load_fashion_mnist()
  print('train_y', train_y[:5])
  print('train_X', train_X.shape)
  num_classes = train_y[0].shape
  print(num_classes)
  model = build_cnn_model(train_X[0].shape,num_classes)

  model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])
  hist = model.fit(train_X,train_y,epochs = epochs)

  test_loss, test_accuracy = model.evaluate(test_X,test_y)
  print(f"test accuracy = {test_accuracy * 100:.3f}%")

if __name__ == "__main__":
  main()

train_y [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
train_X (60000, 28, 28, 1)
(10,)


TypeError: ignored